import React, { useEffect, useState } from 'react';
import { View, Text, StyleSheet, ScrollView, TouchableOpacity, Image, Alert, KeyboardAvoidingView, Platform, ActivityIndicator } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import * as ImagePicker from 'expo-image-picker';
import { Ionicons } from '@expo/vector-icons';
import { Colors } from '../../constants/colors';
import { Header } from '../../components/common/Header';
import { Input } from '../../components/common/Input';
import { Button } from '../../components/common/Button';
import { useAppSelector } from '../../hooks/useAppSelector';
import { submissionsApi } from '../../api/submissionsApi';
import { useNavigation, useRoute } from '@react-navigation/native';
import type { NativeStackNavigationProp } from '@react-navigation/native-stack';
import type { RouteProp } from '@react-navigation/native';
import type { AppStackParamList } from '../../navigation/AppStack';

const CATEGORIES = ['Community', 'Education', 'Environment', 'Health', 'Events'] as const;
type Asset = { uri: string; type: 'image' | 'video'; name: string; mimeType: string };
type Nav = NativeStackNavigationProp<AppStackParamList>;
type Route = RouteProp<AppStackParamList, 'ResubmitNews'>;

export const ResubmitNewsScreen = () => {
  const navigation = useNavigation<Nav>();
  const route = useRoute<Route>();
  const { user } = useAppSelector(s => s.auth);
  const [loading, setLoading] = useState(true); const [submitting, setSubmitting] = useState(false); const [error, setError] = useState('');
  const [title, setTitle] = useState(''); const [description, setDescription] = useState(''); const [location, setLocation] = useState(''); const [date, setDate] = useState(''); const [category, setCategory] = useState<string>('Community'); const [sourceUrl, setSourceUrl] = useState(''); const [feedback, setFeedback] = useState('');
  const [assets, setAssets] = useState<Asset[]>([]);

  useEffect(() => { (async()=>{ try { const res = await submissionsApi.getMySubmission(route.params.id); const n=res.news; setTitle(n.title);setDescription(n.description);setLocation(n.location);setDate(new Date(n.date).toISOString().slice(0,10));setCategory(n.category);setSourceUrl(n.sourceUrl||'');setFeedback(n.rejectionMessage||''); } catch(e:any){setError(e?.response?.data?.message||'Failed to load submission');} finally{setLoading(false);} })(); },[route.params.id]);
  const pickMedia = async () => { const {status}=await ImagePicker.requestMediaLibraryPermissionsAsync(); if(status!=='granted'){Alert.alert('Permission needed','Please allow access to your photo library.');return;} const result=await ImagePicker.launchImageLibraryAsync({mediaTypes:ImagePicker.MediaTypeOptions.All,allowsMultipleSelection:true,selectionLimit:5,quality:0.8,videoMaxDuration:120}); if(result.canceled)return; const mapped=result.assets.map((a:any)=>({uri:a.uri,type:a.type==='video'?'video':'image',name:a.fileName||`media_${Date.now()}.${a.uri.split('.').pop()||'jpg'}`,mimeType:a.mimeType || (a.type==='video'?'video/mp4':'image/jpeg')} as Asset)); setAssets(mapped.slice(0,5)); };
  const submit=async()=>{setError('');if(title.trim().length<10||description.trim().length<20||location.trim().length<2||!date){setError('Please complete all required fields.');return;}const parsed=new Date(date);if(Number.isNaN(parsed.getTime())){setError('Enter a valid date.');return;}if(sourceUrl.trim()&&!/^https?:\/\//i.test(sourceUrl.trim())){setError('Source URL must start with http:// or https://.');return;}const fd=new FormData();fd.append('title',title.trim());fd.append('description',description.trim());fd.append('location',location.trim());fd.append('date',parsed.toISOString());fd.append('category',category);if(sourceUrl.trim())fd.append('sourceUrl',sourceUrl.trim());assets.forEach(a=>fd.append('media',{uri:a.uri,name:a.name,type:a.mimeType} as any));setSubmitting(true);try{await submissionsApi.resubmitNews(route.params.id,fd);Alert.alert('Resubmitted','Your revised story has been sent for review.',[{text:'OK',onPress:()=>navigation.replace('MySubmissions')}]);}catch(e:any){setError(e?.response?.data?.message||'Resubmission failed.');}finally{setSubmitting(false);}};
  if(loading)return <SafeAreaView style={styles.safe}><View style={styles.center}><ActivityIndicator size="large" color={Colors.primary}/></View></SafeAreaView>;
  return <SafeAreaView style={styles.safe}><Header showBack title="Revise Story" subtitle="Update your submission and send it back for review"/><KeyboardAvoidingView style={{flex:1}} behavior={Platform.OS==='ios'?'padding':undefined}><ScrollView contentContainerStyle={styles.content}>{feedback?<View style={styles.feedback}><Ionicons name="information-circle-outline" size={20} color={Colors.error}/><View style={{flex:1}}><Text style={styles.feedbackTitle}>Moderator feedback</Text><Text style={styles.feedbackText}>{feedback}</Text></View></View>:null}{error?<View style={styles.error}><Text style={styles.errorText}>{error}</Text></View>:null}<Text style={styles.label}>Photos & Videos</Text><View style={styles.mediaRow}>{assets.map((a,i)=><View key={i} style={styles.thumbWrap}><Image source={{uri:a.uri}} style={styles.thumb}/>{a.type==='video'&&<View style={styles.videoOverlay}><Ionicons name="play" size={18} color="#fff"/></View>}<TouchableOpacity onPress={()=>setAssets(prev=>prev.filter((_,idx)=>idx!==i))} style={styles.remove}><Ionicons name="close-circle" size={20} color="#fff"/></TouchableOpacity></View>)}{assets.length<5&&<TouchableOpacity style={styles.add} onPress={pickMedia}><Ionicons name="camera-outline" size={26} color={Colors.primary}/><Text style={styles.addText}>Add Media</Text></TouchableOpacity>}</View><Text style={styles.hint}>Upload at most 5 files. Images up to 8 MB each; videos up to 30 MB each.</Text><Input label="Headline *" value={title} onChangeText={setTitle} maxLength={200}/><Text style={styles.counter}>{title.length}/200</Text><Input label="Full Story *" value={description} onChangeText={setDescription} multiline numberOfLines={6} maxLength={5000} style={{minHeight:130}}/><Text style={styles.counter}>{description.length}/5000</Text><Input label="Location *" value={location} onChangeText={setLocation} maxLength={150}/><Input label="Date *" value={date} onChangeText={setDate} placeholder="YYYY-MM-DD"/><Input label="Source URL (optional)" value={sourceUrl} onChangeText={setSourceUrl} autoCapitalize="none" keyboardType="url" placeholder="https://example.org/source"/><Text style={styles.label}>Category *</Text><View style={styles.categories}>{CATEGORIES.map(c=><TouchableOpacity key={c} onPress={()=>setCategory(c)} style={[styles.chip,category===c&&styles.chipActive]}><Text style={[styles.chipText,category===c&&styles.chipTextActive]}>{c}</Text></TouchableOpacity>)}</View><Button title={submitting?'Resubmitting…':'Resubmit for Review'} variant="accent" loading={submitting} disabled={submitting} onPress={submit}/></ScrollView></KeyboardAvoidingView></SafeAreaView>;
};
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:'#fff'},center:{flex:1,justifyContent:'center',alignItems:'center'},content:{padding:18,paddingBottom:60},label:{fontSize:14,fontWeight:'700',color:'#374151',marginBottom:10},mediaRow:{flexDirection:'row',flexWrap:'wrap',gap:10,marginBottom:6},thumbWrap:{width:82,height:82,borderRadius:10,overflow:'hidden',position:'relative'},thumb:{width:'100%',height:'100%'},videoOverlay:{...StyleSheet.absoluteFillObject,backgroundColor:'rgba(0,0,0,.28)',justifyContent:'center',alignItems:'center'},remove:{position:'absolute',right:2,top:2,backgroundColor:'rgba(0,0,0,.4)',borderRadius:10},add:{width:82,height:82,borderRadius:10,borderWidth:2,borderStyle:'dashed',borderColor:Colors.primary,justifyContent:'center',alignItems:'center'},addText:{fontSize:11,color:Colors.primary,fontWeight:'700',marginTop:2},hint:{fontSize:11,color:'#9CA3AF',marginBottom:16},counter:{fontSize:10,color:'#9CA3AF',textAlign:'right',marginTop:-14,marginBottom:12},feedback:{flexDirection:'row',gap:10,padding:12,borderRadius:10,backgroundColor:'#FEF2F2',marginBottom:14},feedbackTitle:{fontSize:13,fontWeight:'700',color:Colors.error,marginBottom:3},feedbackText:{fontSize:12,lineHeight:17,color:'#991B1B'},error:{padding:12,borderRadius:10,backgroundColor:'#FEF2F2',marginBottom:14},errorText:{fontSize:13,color:'#991B1B'},categories:{flexDirection:'row',flexWrap:'wrap',gap:8,marginBottom:24},chip:{paddingHorizontal:12,paddingVertical:8,borderRadius:18,borderWidth:1,borderColor:'#E5E7EB',backgroundColor:'#fff'},chipActive:{backgroundColor:'#EDE9FE',borderColor:'#C4B5FD'},chipText:{fontSize:12,color:'#6B7280'},chipTextActive:{color:Colors.primary,fontWeight:'700'}});
