import React, { useEffect, useState } from 'react';
import { ScrollText } from 'lucide-react';
import { auditApi, AuditLog } from '@/api/auditApi';
import { LoadingSpinner } from '@/components/ui/LoadingSpinner';
import { EmptyState } from '@/components/ui/EmptyState';
import { Pagination } from '@/components/ui/Pagination';
import { Input } from '@/components/ui/Input';
import { safeFormat } from '@/utils/date';

const pretty=(v:unknown)=>{if(v==null||v==='')return '—';if(typeof v==='string')return v;try{return JSON.stringify(v,null,2);}catch{return String(v);}};
const AuditLogsPage:React.FC=()=>{const[items,setItems]=useState<AuditLog[]>([]);const[total,setTotal]=useState(0);const[page,setPage]=useState(1);const[action,setAction]=useState('');const[entityType,setEntityType]=useState('');const[entityId,setEntityId]=useState('');const[loading,setLoading]=useState(true);const limit=25;useEffect(()=>{setLoading(true);auditApi.getAuditLogs({page,limit,action:action||undefined,entityType:entityType||undefined,entityId:entityId||undefined}).then(d=>{setItems(d.logs||[]);setTotal(d.total||0);}).finally(()=>setLoading(false));},[page,action,entityType,entityId]);return <div className="flex flex-col gap-5"><div className="flex items-end justify-between gap-4 flex-wrap"><div><h2 className="text-xl font-bold text-gray-900">Audit Log</h2><p className="text-sm text-muted mt-1">Administrator actions and moderation decisions.</p></div><div className="flex items-end gap-3 flex-wrap"><div className="w-56"><Input label="Action" placeholder="e.g. submission_approved" value={action} onChange={e=>{setAction(e.target.value);setPage(1);}}/></div><div className="w-48"><Input label="Entity Type" value={entityType} onChange={e=>{setEntityType(e.target.value);setPage(1);}}/></div><div className="w-48"><Input label="Entity ID" value={entityId} onChange={e=>{setEntityId(e.target.value);setPage(1);}}/></div></div></div><div className="bg-white rounded-xl border border-gray-100 shadow-sm overflow-hidden">{loading?<div className="py-20"><LoadingSpinner size="lg"/></div>:items.length===0?<EmptyState icon={<ScrollText size={40}/>} title="No audit events" description="Administrator activity will appear here."/>:<><div className="divide-y divide-gray-100">{items.map(log=><div key={log._id} className="p-5"><div className="flex flex-wrap items-center gap-2 mb-2"><span className="font-semibold text-gray-900 capitalize">{log.action.replace(/_/g,' ')}</span><span className="text-xs px-2 py-0.5 rounded-full bg-gray-100 text-gray-600">{log.entityType}</span><span className="text-xs text-muted">{safeFormat(log.createdAt,'MMM d, yyyy HH:mm')}</span><span className="text-xs text-muted ml-auto">{log.admin?.name||'Unknown admin'}</span></div>{log.reason&&<p className="text-sm text-gray-700 mb-3">{log.reason}</p>}<div className="grid md:grid-cols-2 gap-3"><pre className="text-xs bg-gray-50 rounded-lg p-3 overflow-auto max-h-48"><strong>Before</strong>{'\n'}{pretty(log.before)}</pre><pre className="text-xs bg-gray-50 rounded-lg p-3 overflow-auto max-h-48"><strong>After</strong>{'\n'}{pretty(log.after)}</pre></div></div>)}</div><div className="px-4 py-4 border-t border-gray-100"><Pagination page={page} totalPages={Math.ceil(total/limit)} onPageChange={setPage}/></div></>}</div></div>};
export default AuditLogsPage;
